[project]
name = "api"
version = "0.1.0"
description = "Backend API for CodeForge"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.112.0",
    "sqlmodel>=0.0.21",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
